mod day01_no_time_for_a_taxicab;
mod day02_bathroom_security;
mod day03_squares_with_three_sides;
mod day04_security_through_obscurity;
mod day05_how_about_a_nice_game_of_chess;
mod day06_signals_and_noise;
mod day07_internet_protocol_version_7;
