pub mod day01_chronal_calibration;
pub mod day02_inventory_management_system;
pub mod day03_no_matter_how_you_slice_it;
pub mod day04_repose_record;
pub mod day05_alchemical_reduction;
pub mod day06_chronal_coordinates;
pub mod day07_the_sum_of_its_parts;
pub mod day08_memory_maneuver;
pub mod day09_marble_mania;
