mod day01_not_quite_lisp;
mod day02_i_was_told_there_would_be_no_math;
mod day03_perfectly_spherical_houses_in_a_vacuum;
mod day04_the_ideal_stocking_stuffer;
mod day05_doesnt_he_have_intern_elves_for_this;
mod day06_probably_a_fire_hazard;
mod day07_some_assembly_required;
