name: "2020"

on:
  push:
    branches: [ master ]
    paths: [ 2020/ ]
  pull_request:
    branches: [ master ]
    paths: [ 2020/ ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    
    defaults:
      run:
        working-directory: ./2020

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
